### ISSUE TITLE
Arduino UNO

### ISSUE THREAD

**Issue by GhostViper396** [vojtamolda/homebridge-bluetooth#18]
Hey

Anyone ever got this working with UNO and hm-10 dongle?

Got any example code?

Regards

Matt

**Comment by vojtamolda** [comment]
Hello Matt,

Yes, _homebridge-bluetooth_ works on the _UNO_. The list of supported devices is a bit further down the [FAQ](https://github.com/vojtamolda/homebridge-bluetooth#on-what-devices-was-this-plugin-tested) section of the `readme.md` file.

Regarding the dongle - I can't be much of help there, because I've tested only on _macOS_ or _Linux Raspberry Pi 3_ that have the _BLE 4_ dongles built-in. Generally any _BLE 4_ dongle recognized by the OS should work. Check out the requirements of the [_noble_](https://github.com/noble/noble) project for more details.

All the sketches in the [`examples/`](https://github.com/vojtamolda/homebridge-bluetooth/tree/master/examples) folder for _Arduino 101_ work with _Arduino UNO_ and a compatible _nRF8001_ board. In particular, I've used [_Adafruit's nRF8001 Breakout_](https://www.adafruit.com/product/1697) for my tests.

I'd recommend starting with the [`examples/lightbulb`](https://github.com/vojtamolda/homebridge-bluetooth/tree/master/examples/lightbulb) which essentially allows the internal LED to be controlled over _BLE_. A small adjustment is needed at the top of the file to make the sketch work:

```c
#include <Arduino.h>
#include <SPI.h> // nRF8001 communicates over SPI
#include <BLEPeripheral.h> // replace CurieBLE

const int pinLED = 13;
const int pinREQ = 3; // nRF8001 REQ pin
const int pinRDY = 4; // nRF8001 RDY pin
const int pinRST = 5; // nRF8001 RST pin

BLEPeripheral ble(pinREQ, pinRDY, pinRST);
... // Rest of the file is the same
```

Also, keep in mind that the _BLEPeripheral_ library is quite big and uses about 80% of the _UNO_. You'll have ~500 bytes of FLASH available for you local variables (including strings) so too many other bells and whistles will crash your app.

Please, feel free to submit a pull request for the example with an Arduino IDE `*.ino` sketch or even a Fritzing `*.fzz` connection schematics.
