### ISSUE TITLE
Issue with initializing accessory

### ISSUE THREAD

**Issue by fYaH-r0ze** [vojtamolda/homebridge-bluetooth#2]
Good Day,

After some reinstalls of homebridge I was able to get your plugin installed. However, I seems to be getting the following error when running home bridge with your accessory sample:

```
[11/12/2016, 11:37:05 PM] ---
[11/12/2016, 11:37:05 PM] Loaded config.json with 1 accessories and 0 platforms.
[11/12/2016, 11:37:05 PM] ---
[11/12/2016, 11:37:05 PM] Loading 1 accessories...
[11/12/2016, 11:37:05 PM] [Arduino 101] Initializing BLE Accessory accessory...
/usr/local/lib/node_modules/homebridge-bluetooth/index.js:18
  this.lights.service = trim_uuid(config.lights.service);
                                               ^
TypeError: Cannot read property 'service' of undefined
    at new BLEAccessory (/usr/local/lib/node_modules/homebridge-bluetooth/index.js:18:48)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:262:29)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:78:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

Any thoughts?

**Comment by vojtamolda** [comment]
Hello @fallenfate1982,

Please, bear with me for a moment. You're one of the first users of this plugin, so there are still some rough edges to work on. The whole thing is my side project and I work on it whenever my wife lets me out of the leash 😃 The first official [version on npm](https://www.npmjs.com/package/homebridge-bluetooth) - `0.0.0` is a snapshot of an essentially empty repository and I didn't expect that there would be real people using this.

I apologize for the problem you're having. It's caused by my rapid (Some people may even say chaotic...) development. The `config.json` example probably doesn't match the code or some other kind of mismatch. I rewrote the whole plugin more or less from scratch to take advantage of the newer [homebridge platform API](https://github.com/nfarina/homebridge/wiki/On-Programming-Platforms). The most recent version can be found in the [develop branch](https://github.com/vojtamolda/homebridge-bluetooth/tree/develop), so you an try your luck using latest there if you don't want to wait.

I plan to release the first public version (probably `0.1.0`) this evening (US Central Time). This version will come with two working examples of a BLE lightbulb that you can use and I promise they will really work. You can install it easily with `npm update homebridge-bluetooth`.

I'll be happy if you provide some feedback on how you like the new version.

**Comment by fYaH-r0ze** [comment]
LOL ok, I understand. 

I did end up spending a good bit of time reworking the one from npm install. 

I don't know if you're using a mac and solved this issue, but I can't seem to get the write to BLE to work even if I do it directly from noble. Mind you, all else is working fine now -detect, read of the characteristics etc. 

The write works if I use light blue or the companion app I developed for the device. So my issue is either I'm not using noble correctly, or there's a bug in there with the write re my platform (macOS Serria) - you can see the issue I'm having here:
https://github.com/sandeepmistry/noble/issues/499

I'll take a look at that branch code as well to see if it lines up with what I ended up learning and doing today! If you can steer me in the direction that would be great! Hopefully I may be able to help you someday expand this as well!

**Comment by vojtamolda** [comment]
I apologize for the trouble - the problem you're having is resolved in the `0.1.0` version. I published it to [npm](https://www.npmjs.com/package/homebridge-bluetooth) yesterday evening.

The best way to get started is to take a look into the [refreshed examples](https://github.com/vojtamolda/homebridge-bluetooth/blob/master/examples/) directory. If you're familiar with writing/reading BLE characteristics it should be fun to get the [Ligthbulb](https://github.com/vojtamolda/homebridge-bluetooth/blob/master/examples/lightbulb/) example to work with your _mbed_ peripheral device. It's just a matter of matching 3 things:
- [x] _Lightbulb_ service/ _On_ characteristic UUID - `config.json`
- [x] Permissions - `read`/`write`/`notify`
- [x] Data type - `BOOL`

The list of [all available HomeKit types](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js) contains both the data type and needed permissions. You can find also a few more details in the [readme.md](https://github.com/vojtamolda/homebridge-bluetooth/blob/master/readme.md) file of the repository.

Good luck with the _noble_ write issue you're having!

**Comment by fYaH-r0ze** [comment]
OK, does your stuff use noble to do the writes to the BLE device? It seemed that way which is why I was investigating noble.

**Comment by fYaH-r0ze** [comment]
OK it seems that it does use noble. I'll still check it out and see if it works through your code.

**Comment by vojtamolda** [comment]
Correct. It uses _noble_ exclusively for all the Bluetooth business.

**Comment by fYaH-r0ze** [comment]
Hmm ok, did you test it on : Macbook Air (2015) & iMac (2012) running macOS 10.12?

I see these listed. I'm also on macOS 10.12, but noble does not seem to write.

I also see you are using the standard write with response? Do you know if that would make a difference? Currently it seems that I implemented my device firmware with write without response.

**Comment by vojtamolda** [comment]
I tested it on iMac 10.12, but the Macbook Air was 10.11 at the time (it was some time ago), but I don't think your issue is caused by the slight differences between 10.11 and 10.12

The call to _noble_ `write(...)` API is in [`source/characteristic.js`](https://github.com/vojtamolda/homebridge-bluetooth/blob/master/source/characteristic.js#L91) and it's done with `withoutResponse = false`.

**Comment by fYaH-r0ze** [comment]
Hey, I was finally able to test your code today. The write seems to work fine now with some tweaks for my devices (have no idea why it still won't work from Noble Directly, I think it may be the encoding - yours is quite a bit more elegant).

I have a new problem that is related to initializing the accessory. It seems to do this sometimes. It will work fine for a couple on/offs from the home kit app. But then it just won't work. 

I noticed the following on the HomeBridge Console when it does NOT work (i.e., characteristic not written to):

```
EventedHTTPServer [::ffff:192.168.1.100] HTTP request: /characteristics +12s
HAPServer [CC:22:3D:E3:CE:31] HAP Request: PUT /characteristics +0ms
Accessory [LifeBot Home] Processing characteristic set: [{"aid":2,"iid":14,"value":1}] +0ms
Accessory [LifeBot Home] Setting Characteristic "On" to value 1 +0ms
EventedHTTPServer [::ffff:192.168.1.100] Muting event '2.14' notification for this connection since it originated here. +1ms
```

When it does work, I get the following instead (which I can fine in your code):

```
EventedHTTPServer [::ffff:192.168.1.100] HTTP request: /characteristics +4s
HAPServer [CC:22:3D:E3:CE:31] HAP Request: PUT /characteristics +0ms
Accessory [LifeBot Home] Processing characteristic set: [{"aid":2,"iid":14,"value":0}] +0ms
Accessory [LifeBot Home] Setting Characteristic "On" to value 0 +0ms
[11/23/2016, 5:30:07 PM] [LightBot] [Front Light] [On] bool
[11/23/2016, 5:30:07 PM] [LightBot] [Front Light] [On] Argh! Set | 01
 ```

I "think" it may be something to do with a timeout if the accessory takes a little longer to respond it just bypasses and goes ahead as though it worked.  

Do you have any thoughts on where I should be looking?

**Comment by vojtamolda** [comment]
Hello @fallenfate1982,

I've never encountered this error behavior before. Did you try the usual business of deleting the `persist` directory inside of `~/.homebridge/` folder? It might be caused by some leftover configs that always happen during development. Homebridge has a session-to-session persist mechanism that causes all kinds of weird trouble.

What version of the plugin are you using?

BTW, Did I forget something somewhere as usual? :smiley:  Or are the the _"bool"_ and _"Argh!"_ your debugging logs?

**Comment by fYaH-r0ze** [comment]
LOL - yeah I had some of my debug stuff in there while I was trying to learn how your code works.

I tried your suggestion, didn't help.

Everything should be the latest versions as of last week when you said that you published the new update.

What I'm seeing is that the issue is two part : 
1. The issue of the accessory not getting the command is definitely based on BLE's range and should be related to some timeout configured in Home Bridge/the plugin. For instance, if the BLE device (in range but potentially a few meters away) takes too long (above 2 sec) to be discovered, the issue occurs.

2. So the communication to the device does not happen, but home bridge reports to homekit as though it did. This is less a concern for me at the moment and will look into it after we track down point 1. 


Can you help me with point 1 as I'm not sure how the code works with home bridge and your plugin 100%. I'm looking for the point where the accessory is set by homekit and homebridge / your plugin kicks off the search for the hardware with Noble. My guess is that there may be a timeout that needs to be extended OR that the search for the device is kicked off in a different thread and is not chained properly with the callback that will then get the services, chars and then do the write. So if the search takes too long (more than a few seconds) the main code runs without the BLE device pointer or something.

I used LightBlue on the same computer that is running homebridge and when devices are in a range that LightBlue takes a couple seconds to find I get the issue. If the device is placed where light blue finds it instantaneously, it works fine.

**Comment by vojtamolda** [comment]
`Noble` scanning starts in [platform.js](https://github.com/vojtamolda/homebridge-bluetooth/blob/master/source/platform.js#L47) inside of the `didFinishLaunching(...)` function. There's no timeout, though. The plugin tells `Noble` to keep scanning until all devices defined in the `config.json` file are found. Scanning is also resumed if any of the devices disconnects.

**Comment by fYaH-r0ze** [comment]
Ok, but when I send a command to a device - like switch on the lights in homekit, where is the code that fires in homebridge that looks for the device at that point and connects->discover Services -> Discover characteristics -> Write to Char... Based on the behavior, it does not seem to find the device to start the process sometimes (again, still in BLE range, but a bit further)

**Comment by vojtamolda** [comment]
That's a good point. The plugin should probably output the signal strength (RSSI) when it discovers a new device. I've opened a separate enhancement issue #3 for this.

**Comment by fYaH-r0ze** [comment]
Yup, but it should also let home kit know that it was unsuccessful in finding/connecting to the device.

My actual issue is with this though, is that for sending the command, home bridge does not seem to spend very long trying to find the device to connect / write to it. I concluded this as I tested with other BLE applications on the same computer - where hombridge does not connect and actually issue the command, other programs were able to do this, however they took a bit longer. Distance was kept constant and does a few times.

As far as I could tell, the plugin or home bridge does not seem to tell home kit that they were unsuccessful in switching off the light, that they were not able to find/connect to the device. NOTE though, the code in platform.js you pointed out DOES find the device because its a constant scan. So the device is found for setting up on start up BUT sometimes when a command is sent, its not found and home kit reports success.

**Comment by fYaH-r0ze** [comment]
I'll be working on this again this weekend, so if you are able to point me to the code I may be able to help track down the code changes that may need to be made for this as well

**Comment by vojtamolda** [comment]
Hello @fallenfate1982

I'm a little bit lost in all the issues and comments here. It's probably caused by my chaotic and sporadic development of the plugin, so I apologize for that. Are you still experiencing issues with initialization described in the first comment? Or can I close this issue and the problem lies in something else?

Regarding issue #3 - I added a new comment with some hints on where to start, if you want to tackle it.

**Comment by fYaH-r0ze** [comment]
Yup, I think this is closed. As well I think the issue with the distance may be the plugin maintaining a bluetooth connection with the bridge rather than pure distance. I mentioned this in issue 4 and we can dig into details there on that one, so I'll close this.

**Comment by vojtamolda** [comment]
:+1:
