### ISSUE TITLE
GarageMate Bluetooth accessory - How to configure?

### ISSUE THREAD

**Issue by keith721** [vojtamolda/homebridge-bluetooth#9]
I have a GarageMate (https://www.bluemate.com/) Bluetooth device that triggers my garage door opener, and I've been able to successfully pair it with my Raspberry Pi running **homebridge**.  Using the **gatttool** utility, I was able to obtain the primary services and characteristics of the GarageMate device.  Now, I'm attempting to update my config.json configuration file with the proper information.  Unfortunately, it's not going well.  The homebridge-bluetooth platform aborts.

GarageMate explained that reading Core Characteristic 0x2A57 from Core Service 0x1815 would activate the device.  These are the UUID values I was able to obtain from gatttool:
```
attr handle: 0x0039, end grp handle: 0xffff uuid: 00001815-0000-1000-8000-00805f9b34fb
handle: 0x003a, char properties: 0x0a, char value handle: 0x003b, uuid: 00002a57-0000-1000-8000-00805f9b34fb
```

The GarageMate implements a momentary contact closure via two wires to the garage door opener.  It doesn't understand in any manner whether the door is open or closed or blocked.  In my understanding, it's a simple button-press.  I'd expect to configure it as follows:

```
"name": "GarageMate",
"address": "01:23:45:67:89:AB",
"services": [ {
    "name": "Garage Door",
    "type": "Automation_IO",
    "UUID": "00001815-0000-1000-8000-00805f9b34fb",
    "characteristics": [ {
        "type": "Button",
        "UUID": "00002a57-0000-1000-8000-00805f9b34fb"
      } ]
   } ]
```
Thank you for your assistance!

**Comment by vojtamolda** [comment]
Hello @keith721,

Your `config.json` is almost correct. All the `"type"` fields must match a _HomeKit_ service/characteristic from [`HomeKitTypes.js`](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js). This `config.json` will consider the device to be a _HomeKit_ switch:

```js
"name": "GarageMate",
"address": "01:23:45:67:89:AB",
"services": [ {
    "name": "Garage Door",
    "type": "Switch",
    "UUID": "00001815-0000-1000-8000-00805f9b34fb",
    "characteristics": [ {
        "type": "On",
        "UUID": "00002a57-0000-1000-8000-00805f9b34fb"
      } ]
   } ]
```

You can find more details about these by reading the defintion of [`Service.Switch`](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L3120) and it's only mandatory member [`Characteristic.On`](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L1235).

Try if this works and get back here. `Characteristic.On` is should support `read`, `write` and `notify` operations. If the _GarageMate_ really triggers the door only by reading the characteristic, then get ready for a a lot of opening. The switch state is read every time you try to access it in the _Home_ app on your iphone/ipad.

To be honest the plugin was never intended to be this general and allow _BLE_ service to map onto a _HomeKit_ service with some form of a translation happening in between. I like to push the boundaries and the change to the codebase of this plugin in order to incorporate this kind of general mapping is substantial, but it's definitely doable.

If you take a look at the examples, all of them have access to the source code running on the _BLE_ peripheral and make the BLE services/characteristics match _HomeKit_. In this case I doubt GarageMate will release and open-source their firmware, so that's not an option.

**Comment by keith721** [comment]
After reviewing [Service.Switch](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L3120) and [Characteristic.On](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L1235), it appears the GarageMate device should be configured as [Service.StatelessProgrammableSwitch](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L3099) instead of [Service.Switch](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L3120).  Hopefully, this would avoid "a lot of opening".

I'll work with this when I return home this evening and have access to the GarageMate device.  If all else fails, I can always attempt to implement similar behavior using an Arduino.  Thank you!

**Comment by vojtamolda** [comment]
Yeah. You're right. The `StatelessProgrammableSwitch` seems like a better choice. To be honest, there's so many services in _HomeKit_ I didn't even know this one existed... :smile:

Good luck and have fun in the evening!

**Comment by keith721** [comment]
Thank you SO VERY MUCH for your help today.  I sincerely appreciate it.

If I can get the existing GarageMate device working tonight, it's because of your assistance.
If not, then I'll program an Arduino sketch using your very generous examples to get started.
Either way, your assistance has been extremely inspirational.

Thanks!!

**Comment by vojtamolda** [comment]
:blush:

**Comment by keith721** [comment]
I got it configured and the config parsed and loaded successfully, but it's "not supported" in the Home app on my iPhone. :(

```
[3/13/2017, 6:58:07 PM] [Bluetooth] Started | poweredOn
[3/13/2017, 6:58:07 PM] [Bluetooth] [GarageMate] Connected | GarageMate (98:7B:F3:62:C1:43)
[3/13/2017, 6:58:08 PM] [Bluetooth] [GarageMate] [Information] Connected
[3/13/2017, 6:58:08 PM] [Bluetooth] [GarageMate] [Information] [Model] Connected
[3/13/2017, 6:58:08 PM] [Bluetooth] [GarageMate] [Information] [SerialNumber] Connected
[3/13/2017, 6:58:08 PM] [Bluetooth] [GarageMate] [Information] [Manufacturer] Connected
[3/13/2017, 6:58:12 PM] [Bluetooth] [GarageMate] [Information] [Manufacturer] Disconnected
[3/13/2017, 6:58:12 PM] [Bluetooth] [GarageMate] [Information] [Model] Disconnected
[3/13/2017, 6:58:12 PM] [Bluetooth] [GarageMate] [Information] [SerialNumber] Disconnected
[3/13/2017, 6:58:12 PM] [Bluetooth] [GarageMate] Disconnected
[3/13/2017, 6:58:13 PM] [Bluetooth] [GarageMate] Connected | GarageMate (98:7B:F3:62:C1:43)
[3/13/2017, 6:58:13 PM] [Bluetooth] [GarageMate] [Information] Connected
[3/13/2017, 6:58:13 PM] [Bluetooth] [GarageMate] [Information] [Model] Connected
[3/13/2017, 6:58:13 PM] [Bluetooth] [GarageMate] [Information] [SerialNumber] Connected
[3/13/2017, 6:58:13 PM] [Bluetooth] [GarageMate] [Information] [Manufacturer] Connected
[3/13/2017, 6:58:18 PM] [Bluetooth] [GarageMate] [Information] [Manufacturer] Disconnected
[3/13/2017, 6:58:18 PM] [Bluetooth] [GarageMate] [Information] [Model] Disconnected
[3/13/2017, 6:58:18 PM] [Bluetooth] [GarageMate] [Information] [SerialNumber] Disconnected
[3/13/2017, 6:58:18 PM] [Bluetooth] [GarageMate] Disconnected
[3/13/2017, 6:58:19 PM] [Bluetooth] [GarageMate] Connected | GarageMate (98:7B:F3:62:C1:43)
[3/13/2017, 6:58:19 PM] [Bluetooth] [GarageMate] [Information] Connected
[3/13/2017, 6:58:19 PM] [Bluetooth] [GarageMate] [Information] [Model] Connected
[3/13/2017, 6:58:19 PM] [Bluetooth] [GarageMate] [Information] [SerialNumber] Connected
[3/13/2017, 6:58:19 PM] [Bluetooth] [GarageMate] [Information] [Manufacturer] Connected
noble warning: unknown handle 64 disconnected!
noble: unknown peripheral d0034b1f24e5 connected!
noble: unknown peripheral d0034b1f24e5 disconnected!
[3/13/2017, 6:58:24 PM] [Bluetooth] [GarageMate] [Information] [Manufacturer] Disconnected
[3/13/2017, 6:58:24 PM] [Bluetooth] [GarageMate] [Information] [Model] Disconnected
[3/13/2017, 6:58:24 PM] [Bluetooth] [GarageMate] [Information] [SerialNumber] Disconnected
[3/13/2017, 6:58:24 PM] [Bluetooth] [GarageMate] Disconnected
```

Here's the relevant portion of my config.json:

```
	    "platform" : "Bluetooth",
	    "name" : "Bluetooth",
	    "accessories" : [ {
		"name" : "GarageMate",
		"address" : "98:7B:F3:62:C1:43",
		"services" : [ {
		    "name" : "Garage Door",
		    "type" : "StatelessProgrammableSwitch",
		    "UUID" : "00001815-0000-1000-8000-00805f9b34fb",
		    "characteristics": [ {
			"type" : "ProgrammableSwitchEvent",
			"UUID" : "00002a57-0000-1000-8000-00805f9b34fb"
		    } ]
		} ]
	    } ]
```

**Comment by vojtamolda** [comment]
First, _HomeKit_ is still being actively developed on all fronts and you're right that the current _iOS_ (10.2) doesn't support the `StatelessProgrammableSwitch` service. However, according to [this issue](https://github.com/ebaauw/homebridge-hue/issues/54) the support will be added in 10.3. And there's not much else one can do about this than to wait for Apple.

Second, even if _iOS_ would support the switch I don't think it would work with the _GarageMate_. I tried googling to fill my knowledge gap about switches. `StatelessProgrammableSwitch` is a simple push button that returns back to it's original position after being pressed. It's meant as an event generator for the _HomeKit_ ecosystem that can trigger other things. That's why it supports only `READ` and `NOTIFY` operations. There's a detailed (and loooong) discusion [here](https://github.com/KhaosT/HAP-NodeJS/issues/134).

Third, there's a very weird sequence of rapid BLE connect-disconnect events in your log. This shouldn't happen. Normally the plugin should connect only once and stay connected to the peripheral. I'm not sure why is this happening and the disconnect happens after reading the manufacturer string, which is quite innocent operation. Can you try running _Homebridge_ in debug mode and posting the log here, please?

```sh
DEBUG=* homebridge
```

It's a shame the _GarageMate_ doesn't work. Make this puzzle piece fit the rest of the _HomeKit_ ecosystem is much harder nut to crack than I expected. So maybe going for the DIY solution and using the _Arduino 101_  or a similar board will get the door working for you faster...

**Comment by keith721** [comment]
I also noticed the GarageMate did not provide the [Device Information service 0x180A](https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.service.device_information.xml) or its characteristics of [Manufacturer Name 0x2A29](https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.characteristic.manufacturer_name_string.xml), [Model Number 0x2A24](https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.characteristic.model_number_string.xml), and [Serial Number 0x2A25](https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.characteristic.serial_number_string.xml).    Because of this, I ordered an Arduino UNO, HM-10 BLE Bluetooth 4.0 module, and switch/relay board.  I've already developed the Arduino sketch to emulate the GarageMate device.  My hope is that using the more up-to-date [CurieBLE library](https://www.arduino.cc/en/Reference/CurieBLE) may resolve the disconnect/reconnect issues.

**Comment by vojtamolda** [comment]
Those services are not mandatory and the plugin can work fine without them. But anyway, I'll be happy to merge a pull request with a new example if you want to make it.

**Comment by keith721** [comment]
It will be some weeks before my parts arrive.  When I've had some opportunity to test the script and work out any bugs, I'll be happy to submit it here.  Meanwhile, I believe I can close this question.  Thanks again for your generous assistance!
